export default function VisetosPattern() {
  return (
    <svg
      width="100%"
      height="100%"
      xmlns="http://www.w3.org/2000/svg"
      style={{ position: "absolute", inset: 0 }}
    >
      <defs>
        <pattern
          id="vis"
          x="0"
          y="0"
          width="60"
          height="60"
          patternUnits="userSpaceOnUse"
        >
          <circle
            cx="30"
            cy="30"
            r="9"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.7"
            opacity="0.4"
          />
          <circle
            cx="30"
            cy="30"
            r="4"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.4"
          />
          <circle cx="30" cy="30" r="1.5" fill="#B8924A" opacity="0.5" />
          <line
            x1="30"
            y1="17"
            x2="30"
            y2="43"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.3"
          />
          <line
            x1="17"
            y1="30"
            x2="43"
            y2="30"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.3"
          />
          <line
            x1="21"
            y1="21"
            x2="39"
            y2="39"
            stroke="#B8924A"
            strokeWidth="0.4"
            opacity="0.25"
          />
          <line
            x1="39"
            y1="21"
            x2="21"
            y2="39"
            stroke="#B8924A"
            strokeWidth="0.4"
            opacity="0.25"
          />
          <circle
            cx="0"
            cy="0"
            r="2.5"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.35"
          />
          <circle
            cx="60"
            cy="0"
            r="2.5"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.35"
          />
          <circle
            cx="0"
            cy="60"
            r="2.5"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.35"
          />
          <circle
            cx="60"
            cy="60"
            r="2.5"
            fill="none"
            stroke="#B8924A"
            strokeWidth="0.5"
            opacity="0.35"
          />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#vis)" />
    </svg>
  )
}
